create extension if not exists "pg_cron" with schema "pg_catalog";

drop extension if exists "pg_net";

create sequence "public"."ballots_id_seq";

create sequence "public"."comment_reactions_id_seq";

create sequence "public"."comment_reports_id_seq";

create sequence "public"."comments_id_seq";

create sequence "public"."vote_options_id_seq";

create sequence "public"."votes_id_seq";


  create table "public"."ballots" (
    "id" bigint not null default nextval('public.ballots_id_seq'::regclass),
    "vote_id" bigint not null,
    "option_id" bigint not null,
    "user_id" uuid not null,
    "created_at" timestamp with time zone
      );


alter table "public"."ballots" enable row level security;


  create table "public"."comment_reactions" (
    "id" bigint not null default nextval('public.comment_reactions_id_seq'::regclass),
    "comment_id" bigint not null,
    "user_id" uuid not null,
    "type" text not null,
    "created_at" timestamp with time zone
      );


alter table "public"."comment_reactions" enable row level security;


  create table "public"."comment_reports" (
    "id" bigint not null default nextval('public.comment_reports_id_seq'::regclass),
    "comment_id" bigint not null,
    "reporter_id" uuid not null,
    "reason" text not null,
    "status" text not null,
    "handled_by" uuid,
    "handled_at" timestamp with time zone,
    "notes" text,
    "created_at" timestamp with time zone,
    "updated_at" timestamp with time zone
      );


alter table "public"."comment_reports" enable row level security;


  create table "public"."comments" (
    "id" bigint not null default nextval('public.comments_id_seq'::regclass),
    "vote_id" bigint not null,
    "user_id" uuid not null,
    "parent_id" bigint,
    "body" text not null,
    "visibility" text not null,
    "badge_label" text,
    "likes_count" integer default 0,
    "created_at" timestamp with time zone,
    "updated_at" timestamp with time zone
      );


alter table "public"."comments" enable row level security;


  create table "public"."daily_statistics" (
    "date" date not null,
    "daily_visitors" bigint not null,
    "total_users" bigint not null,
    "daily_votes" bigint not null,
    "daily_comments" bigint not null
      );



  create table "public"."profiles" (
    "id" uuid not null,
    "kakao_user_id" text,
    "display_name" text,
    "role" text not null,
    "gender" text not null,
    "age_group" text not null,
    "created_at" timestamp with time zone,
    "birth_year" bigint
      );


alter table "public"."profiles" enable row level security;


  create table "public"."visitor_logs" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid,
    "ip_address" text,
    "referrer" text,
    "visited_at" timestamp with time zone not null default now()
      );



  create table "public"."vote_options" (
    "id" bigint not null default nextval('public.vote_options_id_seq'::regclass),
    "vote_id" bigint not null,
    "candidate_name" text not null,
    "party" text,
    "image_path" text,
    "position" smallint,
    "descriptions" text[]
      );


alter table "public"."vote_options" enable row level security;


  create table "public"."vote_participants" (
    "vote_id" bigint not null,
    "user_id" uuid not null,
    "alias_code" text not null,
    "created_at" timestamp with time zone
      );



  create table "public"."votes" (
    "id" bigint not null default nextval('public.votes_id_seq'::regclass),
    "title" text not null,
    "details" text,
    "status" text not null,
    "starts_at" timestamp with time zone not null,
    "ends_at" timestamp with time zone not null,
    "created_by" uuid
      );


alter table "public"."votes" enable row level security;

alter sequence "public"."ballots_id_seq" owned by "public"."ballots"."id";

alter sequence "public"."comment_reactions_id_seq" owned by "public"."comment_reactions"."id";

alter sequence "public"."comment_reports_id_seq" owned by "public"."comment_reports"."id";

alter sequence "public"."comments_id_seq" owned by "public"."comments"."id";

alter sequence "public"."vote_options_id_seq" owned by "public"."vote_options"."id";

alter sequence "public"."votes_id_seq" owned by "public"."votes"."id";

CREATE UNIQUE INDEX ballots_pkey ON public.ballots USING btree (id);

CREATE UNIQUE INDEX ballots_vote_id_user_id_key ON public.ballots USING btree (vote_id, user_id);

CREATE UNIQUE INDEX comment_reactions_comment_id_user_id_key ON public.comment_reactions USING btree (comment_id, user_id);

CREATE UNIQUE INDEX comment_reactions_pkey ON public.comment_reactions USING btree (id);

CREATE UNIQUE INDEX comment_reports_pkey ON public.comment_reports USING btree (id);

CREATE UNIQUE INDEX comments_pkey ON public.comments USING btree (id);

CREATE UNIQUE INDEX daily_statistics_pkey ON public.daily_statistics USING btree (date);

CREATE UNIQUE INDEX profiles_kakao_user_id_key ON public.profiles USING btree (kakao_user_id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX visitor_logs_pkey ON public.visitor_logs USING btree (id);

CREATE INDEX visitor_logs_user_id_idx ON public.visitor_logs USING btree (user_id);

CREATE INDEX visitor_logs_visited_at_idx ON public.visitor_logs USING btree (visited_at);

CREATE UNIQUE INDEX vote_options_id_vote_id_key ON public.vote_options USING btree (id, vote_id);

CREATE UNIQUE INDEX vote_options_pkey ON public.vote_options USING btree (id);

CREATE UNIQUE INDEX vote_options_vote_id_position_key ON public.vote_options USING btree (vote_id, "position");

CREATE UNIQUE INDEX vote_participants_pkey ON public.vote_participants USING btree (vote_id, user_id);

CREATE UNIQUE INDEX vote_participants_vote_id_alias_code_key ON public.vote_participants USING btree (vote_id, alias_code);

CREATE UNIQUE INDEX votes_pkey ON public.votes USING btree (id);

alter table "public"."ballots" add constraint "ballots_pkey" PRIMARY KEY using index "ballots_pkey";

alter table "public"."comment_reactions" add constraint "comment_reactions_pkey" PRIMARY KEY using index "comment_reactions_pkey";

alter table "public"."comment_reports" add constraint "comment_reports_pkey" PRIMARY KEY using index "comment_reports_pkey";

alter table "public"."comments" add constraint "comments_pkey" PRIMARY KEY using index "comments_pkey";

alter table "public"."daily_statistics" add constraint "daily_statistics_pkey" PRIMARY KEY using index "daily_statistics_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."visitor_logs" add constraint "visitor_logs_pkey" PRIMARY KEY using index "visitor_logs_pkey";

alter table "public"."vote_options" add constraint "vote_options_pkey" PRIMARY KEY using index "vote_options_pkey";

alter table "public"."vote_participants" add constraint "vote_participants_pkey" PRIMARY KEY using index "vote_participants_pkey";

alter table "public"."votes" add constraint "votes_pkey" PRIMARY KEY using index "votes_pkey";

alter table "public"."ballots" add constraint "ballots_option_id_vote_id_fkey" FOREIGN KEY (option_id, vote_id) REFERENCES public.vote_options(id, vote_id) ON DELETE CASCADE not valid;

alter table "public"."ballots" validate constraint "ballots_option_id_vote_id_fkey";

alter table "public"."ballots" add constraint "ballots_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."ballots" validate constraint "ballots_user_id_fkey";

alter table "public"."ballots" add constraint "ballots_vote_id_fkey" FOREIGN KEY (vote_id) REFERENCES public.votes(id) ON DELETE CASCADE not valid;

alter table "public"."ballots" validate constraint "ballots_vote_id_fkey";

alter table "public"."ballots" add constraint "ballots_vote_id_user_id_key" UNIQUE using index "ballots_vote_id_user_id_key";

alter table "public"."comment_reactions" add constraint "comment_reactions_comment_id_fkey" FOREIGN KEY (comment_id) REFERENCES public.comments(id) ON DELETE CASCADE not valid;

alter table "public"."comment_reactions" validate constraint "comment_reactions_comment_id_fkey";

alter table "public"."comment_reactions" add constraint "comment_reactions_comment_id_user_id_key" UNIQUE using index "comment_reactions_comment_id_user_id_key";

alter table "public"."comment_reactions" add constraint "comment_reactions_type_check" CHECK ((type = 'like'::text)) not valid;

alter table "public"."comment_reactions" validate constraint "comment_reactions_type_check";

alter table "public"."comment_reactions" add constraint "comment_reactions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."comment_reactions" validate constraint "comment_reactions_user_id_fkey";

alter table "public"."comment_reports" add constraint "comment_reports_comment_id_fkey" FOREIGN KEY (comment_id) REFERENCES public.comments(id) ON DELETE CASCADE not valid;

alter table "public"."comment_reports" validate constraint "comment_reports_comment_id_fkey";

alter table "public"."comment_reports" add constraint "comment_reports_handled_by_fkey" FOREIGN KEY (handled_by) REFERENCES public.profiles(id) ON DELETE SET NULL not valid;

alter table "public"."comment_reports" validate constraint "comment_reports_handled_by_fkey";

alter table "public"."comment_reports" add constraint "comment_reports_reporter_id_fkey" FOREIGN KEY (reporter_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."comment_reports" validate constraint "comment_reports_reporter_id_fkey";

alter table "public"."comment_reports" add constraint "comment_reports_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'hidden'::text, 'rejected'::text]))) not valid;

alter table "public"."comment_reports" validate constraint "comment_reports_status_check";

alter table "public"."comments" add constraint "comments_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES public.comments(id) ON DELETE CASCADE not valid;

alter table "public"."comments" validate constraint "comments_parent_id_fkey";

alter table "public"."comments" add constraint "comments_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."comments" validate constraint "comments_user_id_fkey";

alter table "public"."comments" add constraint "comments_visibility_check" CHECK ((visibility = ANY (ARRAY['active'::text, 'hidden'::text, 'deleted_by_user'::text, 'deleted_by_admin'::text]))) not valid;

alter table "public"."comments" validate constraint "comments_visibility_check";

alter table "public"."comments" add constraint "comments_vote_id_fkey" FOREIGN KEY (vote_id) REFERENCES public.votes(id) ON DELETE CASCADE not valid;

alter table "public"."comments" validate constraint "comments_vote_id_fkey";

alter table "public"."profiles" add constraint "profiles_age_group_check" CHECK ((age_group = ANY (ARRAY['10s'::text, '20s'::text, '30s'::text, '40s'::text, '50s'::text, '60s_plus'::text, 'unknown'::text]))) not valid;

alter table "public"."profiles" validate constraint "profiles_age_group_check";

alter table "public"."profiles" add constraint "profiles_gender_check" CHECK ((gender = ANY (ARRAY['male'::text, 'female'::text, 'other'::text, 'unknown'::text]))) not valid;

alter table "public"."profiles" validate constraint "profiles_gender_check";

alter table "public"."profiles" add constraint "profiles_kakao_user_id_key" UNIQUE using index "profiles_kakao_user_id_key";

alter table "public"."profiles" add constraint "profiles_role_check" CHECK ((role = ANY (ARRAY['user'::text, 'admin'::text]))) not valid;

alter table "public"."profiles" validate constraint "profiles_role_check";

alter table "public"."visitor_logs" add constraint "visitor_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."visitor_logs" validate constraint "visitor_logs_user_id_fkey";

alter table "public"."vote_options" add constraint "vote_options_id_vote_id_key" UNIQUE using index "vote_options_id_vote_id_key";

alter table "public"."vote_options" add constraint "vote_options_vote_id_fkey" FOREIGN KEY (vote_id) REFERENCES public.votes(id) ON DELETE CASCADE not valid;

alter table "public"."vote_options" validate constraint "vote_options_vote_id_fkey";

alter table "public"."vote_options" add constraint "vote_options_vote_id_position_key" UNIQUE using index "vote_options_vote_id_position_key";

alter table "public"."vote_participants" add constraint "vote_participants_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."vote_participants" validate constraint "vote_participants_user_id_fkey";

alter table "public"."vote_participants" add constraint "vote_participants_vote_id_alias_code_key" UNIQUE using index "vote_participants_vote_id_alias_code_key";

alter table "public"."vote_participants" add constraint "vote_participants_vote_id_fkey" FOREIGN KEY (vote_id) REFERENCES public.votes(id) ON DELETE CASCADE not valid;

alter table "public"."vote_participants" validate constraint "vote_participants_vote_id_fkey";

alter table "public"."votes" add constraint "votes_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL not valid;

alter table "public"."votes" validate constraint "votes_created_by_fkey";

alter table "public"."votes" add constraint "votes_status_check" CHECK ((status = ANY (ARRAY['scheduled'::text, 'ongoing'::text, 'closed'::text, 'archived'::text]))) not valid;

alter table "public"."votes" validate constraint "votes_status_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_vote_comments(p_vote_id bigint)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
DECLARE
    result json;
BEGIN
    SELECT json_agg(
        jsonb_build_object(
            'id', c.id,
            'content', c.body,
            'author', p.display_name,
            'badge', c.badge_label,
            'likes', c.likes_count,
            'createdAt', to_char(c.created_at, 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
            'replies', (
                SELECT json_agg(
                    jsonb_build_object(
                        'id', r.id,
                        'content', r.body,
                        'author', rp.display_name,
                        'badge', r.badge_label,
                        'likes', r.likes_count,
                        'createdAt', to_char(r.created_at, 'YYYY-MM-DD"T"HH24:MI:SS"Z"'
                    )
                ) ORDER BY r.created_at ASC)
                FROM comments r
                JOIN profiles rp ON r.user_id = rp.id
                WHERE r.parent_id = c.id AND r.visibility = 'active'
            )
        ) ORDER BY c.created_at DESC
    )
    INTO result
    FROM comments c
    JOIN profiles p ON c.user_id = p.id
    WHERE c.vote_id = p_vote_id AND c.parent_id IS NULL AND c.visibility = 'active';

    RETURN COALESCE(result, '[]'::json); -- Return empty JSON array if no comments found
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_vote_details(p_vote_id bigint)
 RETURNS TABLE(total_count bigint, options jsonb)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$DECLARE
  total_count bigint;
  options jsonb;
BEGIN
  SELECT count(*) INTO total_count
  FROM public.ballots
  WHERE vote_id = p_vote_id;

  SELECT jsonb_agg(
    jsonb_build_object(
      'id', o.id,
      'name', o.candidate_name,
      'imageUrl', o.image_path,
      'descriptions', o.descriptions,
      'count', COALESCE(b.count, 0),
      'percent', ROUND(
        (
          COALESCE(b.count, 0)::numeric / NULLIF(total_count, 0)
        ) * 100,
        1
      )
    )
  ) INTO options
  FROM public.vote_options o
  LEFT JOIN (
    SELECT option_id, count(*) as count
    FROM public.ballots
    WHERE vote_id = p_vote_id
    GROUP BY option_id
  ) b ON o.id = b.option_id
  WHERE o.vote_id = p_vote_id;

  RETURN QUERY SELECT total_count, COALESCE(options, '[]'::jsonb);
END;$function$
;

CREATE OR REPLACE FUNCTION public.get_vote_feed()
 RETURNS TABLE(vote_id bigint, total_count bigint, title text, status text, ends_at timestamp with time zone, options jsonb)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    RETURN QUERY
    WITH vote_counts AS (
        SELECT
            v.id AS vote_id,
            COUNT(b.id) AS total_votes
        FROM votes v
        LEFT JOIN ballots b ON v.id = b.vote_id
        GROUP BY v.id
    ),
    option_counts AS (
        SELECT
            vo.vote_id,
            vo.id AS option_id,
            COUNT(b.id) AS option_votes
        FROM vote_options vo
        LEFT JOIN ballots b ON vo.id = b.option_id
        GROUP BY vo.vote_id, vo.id
    )
    SELECT
        v.id AS vote_id,
        COALESCE(vc.total_votes, 0) AS total_count,
        v.title,
        v.status,
        v.ends_at,
        (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'id', vo.id,
                    'name', vo.candidate_name,
                    'imageUrl', vo.image_path,
                    'count', COALESCE(oc.option_votes, 0),
                    'percent', ROUND(
                        CASE
                            WHEN COALESCE(vc.total_votes, 0) > 0 THEN
                                (COALESCE(oc.option_votes, 0)::numeric / vc.total_votes) * 100
                            ELSE 0
                        END,
                        1
                    )
                )
                ORDER BY vo.id ASC   
            )
            FROM vote_options vo
            LEFT JOIN option_counts oc ON vo.id = oc.option_id
            WHERE vo.vote_id = v.id
        ) AS options
    FROM votes v
    LEFT JOIN vote_counts vc ON v.id = vc.vote_id
    WHERE v.status = 'ongoing'
    ORDER BY total_count DESC;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- 자동 생성 비활성화 (아무 작업도 안 함)
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_report(p_report_id bigint, p_new_status text, p_admin_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_comment_id bigint;
BEGIN
  -- Get the comment_id from the report
  SELECT comment_id INTO v_comment_id
  FROM public.comment_reports
  WHERE id = p_report_id;

  -- Update the report status
  UPDATE public.comment_reports
  SET
    status = p_new_status,
    handled_by = p_admin_id,
    handled_at = now()
  WHERE id = p_report_id;

  -- If the report is approved ('hidden'), hide the comment
  IF p_new_status = 'hidden' THEN
    UPDATE public.comments
    SET visibility = 'hidden'
    WHERE id = v_comment_id;
  END IF;

END;
$function$
;

CREATE OR REPLACE FUNCTION public.is_admin(uid uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = uid AND role = 'admin'
  );
$function$
;

CREATE OR REPLACE FUNCTION public.is_current_user_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
$function$
;

CREATE OR REPLACE FUNCTION public.toggle_like(p_comment_id bigint, p_user_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_reaction_exists boolean;
  v_is_liked boolean;
BEGIN
  -- Check if the user has already liked the comment
  SELECT EXISTS (
    SELECT 1
    FROM public.comment_reactions
    WHERE comment_id = p_comment_id AND user_id = p_user_id AND type = 'like'
  ) INTO v_reaction_exists;

  IF v_reaction_exists THEN
    -- User has liked, so UNLIKE
    -- 1. Delete the reaction
    DELETE FROM public.comment_reactions
    WHERE comment_id = p_comment_id AND user_id = p_user_id AND type = 'like';

    -- 2. Decrement the likes_count
    UPDATE public.comments
    SET likes_count = likes_count - 1
    WHERE id = p_comment_id;

    v_is_liked := false;
  ELSE
    -- User has not liked, so LIKE
    -- 1. Insert the reaction
    INSERT INTO public.comment_reactions (comment_id, user_id, type, created_at)
    VALUES (p_comment_id, p_user_id, 'like', now());

    -- 2. Increment the likes_count
    UPDATE public.comments
    SET likes_count = likes_count + 1
    WHERE id = p_comment_id;

    v_is_liked := true;
  END IF;

  -- Return the new liked status
  RETURN v_is_liked;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_daily_statistics()
 RETURNS void
 LANGUAGE plpgsql
AS $function$DECLARE
         yesterday_date DATE := (NOW() - INTERVAL '1 day')::DATE;
         yesterday_start TIMESTAMPTZ := yesterday_date;
         yesterday_end TIMESTAMPTZ := yesterday_date + INTERVAL '1 day';
     BEGIN
         -- 집계 데이터 삽입
         INSERT INTO public.daily_statistics (date, daily_visitors, total_users, daily_votes, daily_comments)
        SELECT
            yesterday_date,
            -- 1. 일일 방문자 수 (로그인 사용자 우선, 아니면 IP 기준)
            COUNT(DISTINCT COALESCE(user_id::TEXT, ip_address)),
            -- 2. 누적 사용자 수
            (SELECT COUNT(*) FROM auth.users),
            -- 3. 일일 투표 수
            (SELECT COUNT(*) FROM public.votes WHERE starts_at >= yesterday_start AND starts_at < yesterday_end),
            -- 4. 일일 댓글 수
            (SELECT COUNT(*) FROM public.comments WHERE created_at >= yesterday_start AND created_at < yesterday_end)
        FROM public.visitor_logs
        WHERE visited_at >= yesterday_start AND visited_at < yesterday_end
        ON CONFLICT (date) DO UPDATE
        SET
            daily_visitors = EXCLUDED.daily_visitors,
            total_users = EXCLUDED.total_users,
            daily_votes = EXCLUDED.daily_votes,
            daily_comments = EXCLUDED.daily_comments;
    END;$function$
;

grant delete on table "public"."ballots" to "anon";

grant insert on table "public"."ballots" to "anon";

grant references on table "public"."ballots" to "anon";

grant select on table "public"."ballots" to "anon";

grant trigger on table "public"."ballots" to "anon";

grant truncate on table "public"."ballots" to "anon";

grant update on table "public"."ballots" to "anon";

grant delete on table "public"."ballots" to "authenticated";

grant insert on table "public"."ballots" to "authenticated";

grant references on table "public"."ballots" to "authenticated";

grant select on table "public"."ballots" to "authenticated";

grant trigger on table "public"."ballots" to "authenticated";

grant truncate on table "public"."ballots" to "authenticated";

grant update on table "public"."ballots" to "authenticated";

grant delete on table "public"."ballots" to "service_role";

grant insert on table "public"."ballots" to "service_role";

grant references on table "public"."ballots" to "service_role";

grant select on table "public"."ballots" to "service_role";

grant trigger on table "public"."ballots" to "service_role";

grant truncate on table "public"."ballots" to "service_role";

grant update on table "public"."ballots" to "service_role";

grant delete on table "public"."comment_reactions" to "anon";

grant insert on table "public"."comment_reactions" to "anon";

grant references on table "public"."comment_reactions" to "anon";

grant select on table "public"."comment_reactions" to "anon";

grant trigger on table "public"."comment_reactions" to "anon";

grant truncate on table "public"."comment_reactions" to "anon";

grant update on table "public"."comment_reactions" to "anon";

grant delete on table "public"."comment_reactions" to "authenticated";

grant insert on table "public"."comment_reactions" to "authenticated";

grant references on table "public"."comment_reactions" to "authenticated";

grant select on table "public"."comment_reactions" to "authenticated";

grant trigger on table "public"."comment_reactions" to "authenticated";

grant truncate on table "public"."comment_reactions" to "authenticated";

grant update on table "public"."comment_reactions" to "authenticated";

grant delete on table "public"."comment_reactions" to "service_role";

grant insert on table "public"."comment_reactions" to "service_role";

grant references on table "public"."comment_reactions" to "service_role";

grant select on table "public"."comment_reactions" to "service_role";

grant trigger on table "public"."comment_reactions" to "service_role";

grant truncate on table "public"."comment_reactions" to "service_role";

grant update on table "public"."comment_reactions" to "service_role";

grant delete on table "public"."comment_reports" to "anon";

grant insert on table "public"."comment_reports" to "anon";

grant references on table "public"."comment_reports" to "anon";

grant select on table "public"."comment_reports" to "anon";

grant trigger on table "public"."comment_reports" to "anon";

grant truncate on table "public"."comment_reports" to "anon";

grant update on table "public"."comment_reports" to "anon";

grant delete on table "public"."comment_reports" to "authenticated";

grant insert on table "public"."comment_reports" to "authenticated";

grant references on table "public"."comment_reports" to "authenticated";

grant select on table "public"."comment_reports" to "authenticated";

grant trigger on table "public"."comment_reports" to "authenticated";

grant truncate on table "public"."comment_reports" to "authenticated";

grant update on table "public"."comment_reports" to "authenticated";

grant delete on table "public"."comment_reports" to "service_role";

grant insert on table "public"."comment_reports" to "service_role";

grant references on table "public"."comment_reports" to "service_role";

grant select on table "public"."comment_reports" to "service_role";

grant trigger on table "public"."comment_reports" to "service_role";

grant truncate on table "public"."comment_reports" to "service_role";

grant update on table "public"."comment_reports" to "service_role";

grant delete on table "public"."comments" to "anon";

grant insert on table "public"."comments" to "anon";

grant references on table "public"."comments" to "anon";

grant select on table "public"."comments" to "anon";

grant trigger on table "public"."comments" to "anon";

grant truncate on table "public"."comments" to "anon";

grant update on table "public"."comments" to "anon";

grant delete on table "public"."comments" to "authenticated";

grant insert on table "public"."comments" to "authenticated";

grant references on table "public"."comments" to "authenticated";

grant select on table "public"."comments" to "authenticated";

grant trigger on table "public"."comments" to "authenticated";

grant truncate on table "public"."comments" to "authenticated";

grant update on table "public"."comments" to "authenticated";

grant delete on table "public"."comments" to "service_role";

grant insert on table "public"."comments" to "service_role";

grant references on table "public"."comments" to "service_role";

grant select on table "public"."comments" to "service_role";

grant trigger on table "public"."comments" to "service_role";

grant truncate on table "public"."comments" to "service_role";

grant update on table "public"."comments" to "service_role";

grant delete on table "public"."daily_statistics" to "anon";

grant insert on table "public"."daily_statistics" to "anon";

grant references on table "public"."daily_statistics" to "anon";

grant select on table "public"."daily_statistics" to "anon";

grant trigger on table "public"."daily_statistics" to "anon";

grant truncate on table "public"."daily_statistics" to "anon";

grant update on table "public"."daily_statistics" to "anon";

grant delete on table "public"."daily_statistics" to "authenticated";

grant insert on table "public"."daily_statistics" to "authenticated";

grant references on table "public"."daily_statistics" to "authenticated";

grant select on table "public"."daily_statistics" to "authenticated";

grant trigger on table "public"."daily_statistics" to "authenticated";

grant truncate on table "public"."daily_statistics" to "authenticated";

grant update on table "public"."daily_statistics" to "authenticated";

grant delete on table "public"."daily_statistics" to "service_role";

grant insert on table "public"."daily_statistics" to "service_role";

grant references on table "public"."daily_statistics" to "service_role";

grant select on table "public"."daily_statistics" to "service_role";

grant trigger on table "public"."daily_statistics" to "service_role";

grant truncate on table "public"."daily_statistics" to "service_role";

grant update on table "public"."daily_statistics" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."visitor_logs" to "anon";

grant insert on table "public"."visitor_logs" to "anon";

grant references on table "public"."visitor_logs" to "anon";

grant select on table "public"."visitor_logs" to "anon";

grant trigger on table "public"."visitor_logs" to "anon";

grant truncate on table "public"."visitor_logs" to "anon";

grant update on table "public"."visitor_logs" to "anon";

grant delete on table "public"."visitor_logs" to "authenticated";

grant insert on table "public"."visitor_logs" to "authenticated";

grant references on table "public"."visitor_logs" to "authenticated";

grant select on table "public"."visitor_logs" to "authenticated";

grant trigger on table "public"."visitor_logs" to "authenticated";

grant truncate on table "public"."visitor_logs" to "authenticated";

grant update on table "public"."visitor_logs" to "authenticated";

grant delete on table "public"."visitor_logs" to "service_role";

grant insert on table "public"."visitor_logs" to "service_role";

grant references on table "public"."visitor_logs" to "service_role";

grant select on table "public"."visitor_logs" to "service_role";

grant trigger on table "public"."visitor_logs" to "service_role";

grant truncate on table "public"."visitor_logs" to "service_role";

grant update on table "public"."visitor_logs" to "service_role";

grant delete on table "public"."vote_options" to "anon";

grant insert on table "public"."vote_options" to "anon";

grant references on table "public"."vote_options" to "anon";

grant select on table "public"."vote_options" to "anon";

grant trigger on table "public"."vote_options" to "anon";

grant truncate on table "public"."vote_options" to "anon";

grant update on table "public"."vote_options" to "anon";

grant delete on table "public"."vote_options" to "authenticated";

grant insert on table "public"."vote_options" to "authenticated";

grant references on table "public"."vote_options" to "authenticated";

grant select on table "public"."vote_options" to "authenticated";

grant trigger on table "public"."vote_options" to "authenticated";

grant truncate on table "public"."vote_options" to "authenticated";

grant update on table "public"."vote_options" to "authenticated";

grant delete on table "public"."vote_options" to "service_role";

grant insert on table "public"."vote_options" to "service_role";

grant references on table "public"."vote_options" to "service_role";

grant select on table "public"."vote_options" to "service_role";

grant trigger on table "public"."vote_options" to "service_role";

grant truncate on table "public"."vote_options" to "service_role";

grant update on table "public"."vote_options" to "service_role";

grant delete on table "public"."vote_participants" to "anon";

grant insert on table "public"."vote_participants" to "anon";

grant references on table "public"."vote_participants" to "anon";

grant select on table "public"."vote_participants" to "anon";

grant trigger on table "public"."vote_participants" to "anon";

grant truncate on table "public"."vote_participants" to "anon";

grant update on table "public"."vote_participants" to "anon";

grant delete on table "public"."vote_participants" to "authenticated";

grant insert on table "public"."vote_participants" to "authenticated";

grant references on table "public"."vote_participants" to "authenticated";

grant select on table "public"."vote_participants" to "authenticated";

grant trigger on table "public"."vote_participants" to "authenticated";

grant truncate on table "public"."vote_participants" to "authenticated";

grant update on table "public"."vote_participants" to "authenticated";

grant delete on table "public"."vote_participants" to "service_role";

grant insert on table "public"."vote_participants" to "service_role";

grant references on table "public"."vote_participants" to "service_role";

grant select on table "public"."vote_participants" to "service_role";

grant trigger on table "public"."vote_participants" to "service_role";

grant truncate on table "public"."vote_participants" to "service_role";

grant update on table "public"."vote_participants" to "service_role";

grant delete on table "public"."votes" to "anon";

grant insert on table "public"."votes" to "anon";

grant references on table "public"."votes" to "anon";

grant select on table "public"."votes" to "anon";

grant trigger on table "public"."votes" to "anon";

grant truncate on table "public"."votes" to "anon";

grant update on table "public"."votes" to "anon";

grant delete on table "public"."votes" to "authenticated";

grant insert on table "public"."votes" to "authenticated";

grant references on table "public"."votes" to "authenticated";

grant select on table "public"."votes" to "authenticated";

grant trigger on table "public"."votes" to "authenticated";

grant truncate on table "public"."votes" to "authenticated";

grant update on table "public"."votes" to "authenticated";

grant delete on table "public"."votes" to "service_role";

grant insert on table "public"."votes" to "service_role";

grant references on table "public"."votes" to "service_role";

grant select on table "public"."votes" to "service_role";

grant trigger on table "public"."votes" to "service_role";

grant truncate on table "public"."votes" to "service_role";

grant update on table "public"."votes" to "service_role";


  create policy "Allow public read access to ballots"
  on "public"."ballots"
  as permissive
  for select
  to public
using (true);



  create policy "Allow users to insert their own ballot"
  on "public"."ballots"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "Allow users to view their own ballot"
  on "public"."ballots"
  as permissive
  for select
  to authenticated
using ((auth.uid() = user_id));



  create policy "Allow public read access"
  on "public"."comment_reactions"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Allow users to delete their own reaction"
  on "public"."comment_reactions"
  as permissive
  for delete
  to authenticated
using ((auth.uid() = user_id));



  create policy "Allow users to insert their own reaction"
  on "public"."comment_reactions"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "Allow admin to manage reports"
  on "public"."comment_reports"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))))
with check ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));



  create policy "Allow users to insert their own report"
  on "public"."comment_reports"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = reporter_id));



  create policy "Allow admin to SELECT all comments"
  on "public"."comments"
  as permissive
  for select
  to authenticated
using (public.is_admin(auth.uid()));



  create policy "Allow admin to manage comments"
  on "public"."comments"
  as permissive
  for all
  to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));



  create policy "Allow read access to active comments"
  on "public"."comments"
  as permissive
  for select
  to public
using ((visibility = 'active'::text));



  create policy "Allow users to insert their own comments"
  on "public"."comments"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "Allow users to update their own comments"
  on "public"."comments"
  as permissive
  for update
  to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "Allow public read access to profiles"
  on "public"."profiles"
  as permissive
  for select
  to public
using (true);



  create policy "Allow users to insert their own profile"
  on "public"."profiles"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = id));



  create policy "Allow users to update their own profile"
  on "public"."profiles"
  as permissive
  for update
  to authenticated
using ((auth.uid() = id))
with check ((auth.uid() = id));



  create policy "Allow admin to manage vote options"
  on "public"."vote_options"
  as permissive
  for all
  to public
using (public.is_current_user_admin())
with check (public.is_current_user_admin());



  create policy "Allow public read access to vote options"
  on "public"."vote_options"
  as permissive
  for select
  to public
using (true);



  create policy "Allow admin to manage votes"
  on "public"."votes"
  as permissive
  for all
  to public
using (public.is_current_user_admin())
with check (public.is_current_user_admin());



  create policy "Allow authenticated users to insert votes"
  on "public"."votes"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() IS NOT NULL));



  create policy "Allow public read access to votes"
  on "public"."votes"
  as permissive
  for select
  to public
using (true);


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "Allow admin to manage vote-images"
  on "storage"."objects"
  as permissive
  for all
  to authenticated
using (((bucket_id = 'vote-images'::text) AND (EXISTS ( SELECT 1
   FROM public.profiles p
  WHERE ((p.id = auth.uid()) AND (p.role = 'admin'::text))))))
with check (((bucket_id = 'vote-images'::text) AND (EXISTS ( SELECT 1
   FROM public.profiles p
  WHERE ((p.id = auth.uid()) AND (p.role = 'admin'::text))))));



